---
- name: Install Git
  pacman:
          name: git
          state: present
          update_cache: yes
  become: true

- name: Set git user name
  git_config:
          scope: global
          name: user.name
          value: '{{git.user.name}}'

- name: Set git user email
  git_config:
          scope: global
          name: user.email
          value: '{{git.user.email}}'

